### ISSUE TITLE
USER STORY: Register an account

### ISSUE THREAD

**Issue by rowanam** [rowanam/time-traveling#1]
As a **user** I can **register an account** so that **I can access site features**.

## Acceptance Criteria
- There is a link/button on the home screen to register
- On clicking, the user is brought to a form where they can register their details
- Registration is successful and the user is added to the database

## Tasks
- [x] Add "register" link to navbar
- [x] Link is visible when no user is logged in
- [x] Link takes user to a registration form
- [x] Submitting the form adds user to the database
