### ISSUE TITLE
USER STORY: View life map

### ISSUE THREAD

**Issue by rowanam** [rowanam/time-traveling#10]
As a **user** I can **view a map with all of my trips** so that **I can easily see all of the places I have traveled**.

## Acceptance Criteria
- The life map can be accessed from the nav bar for logged in users
- The map shows lines for all of the user's trips
- Only the logged in user's trips are displayed

## Tasks
- [x] Add life map link to navbar for authenticated users
- [x] Create the view and template
- [x] In the view, pass coordinate pair lists from each trip to the template
- [x] Display a map on the page
- [x] Create a polyline for each trip and display all
