### ISSUE TITLE
USER STORY: Login / Logout

### ISSUE THREAD

**Issue by rowanam** [rowanam/time-traveling#2]
As a **user** I can **log in and out** so that **only I can access my data**.

## Acceptance Criteria
- When no user is logged in, there is a "log in" link/button on the home screen
- Only a logged in user can access the trips functionality
- The logged in user can only see their own trips
- When a user is logged in, there is a "log out" link/button on the screen

## Tasks
- [x] When no user is logged in, there is a "login" button in nav, and vice versa
- [x] When clicked, these links take the user to a login or logout page
- [x] Filling out the login/logout forms logs the user in or out
- [x] The user is appropriately redirected to the dashboard or the home page
- [x] The login and logout pages are styled consistently with the rest of the site
