### ISSUE TITLE
USER STORY: Create a trip

### ISSUE THREAD

**Issue by rowanam** [rowanam/time-traveling#3]
As a **user** I can **create a trip with places and dates** so that **I have a record of my travels**.

## Acceptance Criteria
- Only possible for logged-in users
- On the dashboard, there is an "add trip" button
- The button brings the user to a form where they can add trip details
- The form submits successfully and adds the trip to the database

## Tasks
- [x] Create "add trip" button on dashboard
- [x] Allow only authenticated users to access this page
- [x] Create a form, view and template to create a new trip
- [x] On the new trip page, ask the user for a trip title (required) and start and end dates (optional)
- [x] Create a form, view and template to add locations to the new trip
- [x] On the locations page, display a world map
- [x] When the user clicks on an "add location" button, a search bar is added to the map
- [x] When the user selects a location from the map search bar, a new form is added with the location name (editable by the user) and coordinates (hidden)
- [x] Allow the user to reorder locations
- [x] When the user clicks on "create trip", submit all of the location forms to the database as individual records with a foreign key pointing to the current trip
