### ISSUE TITLE
USER STORY: Edit trip

### ISSUE THREAD

**Issue by rowanam** [rowanam/time-traveling#6]
As a **user** I can **edit a trip** so that **I can update information**.

## Acceptance Criteria
- When a trip is clicked on to display more information, there is a button to edit the trip
- The button brings the user to a form with pre-filled information that can be changed
- The order of trip locations can be changed
- On submission the trip record is updated
- The user is redirected to the trip page

## Tasks
- [x] Add an edit button to the trip detail page
- [x] Create a view and template an edit trip page
- [x] Add forms to the page with prefilled data from the current trip
- [x] Trip title, trips dates and location name fields can be changed
- [x] Allow user to reorder locations in the trip
- [x] All user to delete locations in the trip
- [x] Add a "save changes" button
- [x] On submission, all relevant records (trip and locations) are updated correctly
- [x] Redirect the user to the trip detail page
