### ISSUE TITLE
USER STORY: Delete trip

### ISSUE THREAD

**Issue by rowanam** [rowanam/time-traveling#7]
As a **user** I can **delete a trip** so that **I can remove unwanted trips**.

## Acceptance Criteria
- When a trip is clicked on to view more information, there is a button to delete the trip
- The user is required to confirm deletion
- The trip record is successfully deleted
- The user is returned to the dashboard

## Tasks
- [x] Create a delete button on the trip view page that opens a modal
- [x] Create a modal with a message asking for confirmation of deletion, a delete button and a cancel button
- [x] On delete button click, delete the trip record from the database
- [x] Confirm that all associated locations in the trip are also deleted from the database
- [x] Redirect the user to the dashboard
