### ISSUE TITLE
USER STORY: View time-space line

### ISSUE THREAD

**Issue by rowanam** [rowanam/time-traveling#8]
As a **user** I can **view the time-space line of my trip on a map** so that **I can visualize my trip**.

## Acceptance Criteria
- When a trip is clicked on from the dashboard, a map is displayed with the locations of the trip connected by a line
- The locations are connected in the correct order
- The map can be zoomed in/out and moved around to see the path clearly

## Tasks
- [x] Get a list of coordinates from the locations associated with the current trip, by order
- [x] Load and render a world map on the trip detail page
- [x] Create and render a polyline of the trip coordinates on the map
- [x] Style the map so it is useable and looks consistent with the rest of the site
