### ISSUE TITLE
USER STORY: Upload image

### ISSUE THREAD

**Issue by rowanam** [rowanam/time-traveling#9]
As a **user** I can **upload trip cover images** so that **I can have a visual reminder of my trip**.

## Acceptance Criteria
- Trip creation form contains an upload image field
- The user can select an image from their library
- The image is displayed in the trip card on the dashboard

## Tasks
- [x] Add Cloudinary image field to trip model
- [x] Set up Cloudinary to store images
- [x] Add cover image to dashboard template
- [x] Style image size and fit in card
